### ISSUE TITLE
ERROR: Permission denied for user: 'None'. [Remote: minres]

### ISSUE THREAD

**Issue by felix-boeseler** [Minres/HIFIVE1-VP#1]
Hello,
I tried to build the VP but I got the following error when used `MAKE_FLAGS="-j4" cmake ..`:
`ERROR: Permission denied for user: 'None'. [Remote: minres]`
According to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ the bintray services have been discontinued. Is there any update on how I can build the project?
Many regards and many thanks in advance.

**Comment by eyck** [comment]
We moved to a self hosted artifactory hlding the packages. But this requires some changes and updates to the build system as we also moved to packges from conan-center.
I'll see if I can provide an update of this VP soon. Alternatively you can try https://github.com/Minres/TGC-VP. It has the same structure, only it does have a simpler top level. You may try it out using gitpod.io (see the [README.md](https://github.com/Minres/TGC-VP/blob/main/README.md) there)
